# config.yaml

credentials:
  usernames:
    jsmith:
      email: jsmith@example.com
      name: John Smith
      password: 'abc' # Passwords should be hashed in a real app
    rdoe:
      email: rdoe@example.com
      name: Rebecca Doe
      password: 'def'
cookie:
  expiry_days: 30
  key: 'random_signature_key' # Replace with your own secret key
  name: 'random_cookie_name'
preauthorized:
  emails:
  - jsmith@example.com
  - rdoe@example.com# config.yaml

credentials:
  usernames:
    jsmith:
      email: jsmith@example.com
      name: John Smith
      password: 'abc' # Passwords should be hashed in a real app
    rdoe:
      email: rdoe@example.com
      name: Rebecca Doe
      password: 'def'
cookie:
  expiry_days: 30
  key: 'random_signature_key' # Replace with your own secret key
  name: 'random_cookie_name'
preauthorized:
  emails:
  - jsmith@example.com
  - rdoe@example.com