# .streamlit/secrets.toml

# Your Google API Key
GOOGLE_API_KEY = "AIzaSyATEke0ZozoiVNKiJyHwmlADiPSqp9OvEE"

# Your Firebase Service Account Credentials
# Open the JSON file you downloaded from Firebase, copy everything,
# and paste it between the triple quotes below.
firebase_service_account = """
{
  "type": "service_account",
  "project_id": "ai-interviewer-94aa7",
  "private_key_id": "2487dece3ff5ce2b90493f115c4c41df473f17bb",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCwB+G/kM04K7Em\nmK8TMiLh7APQKXkePmOc33g5M/526bQcZ/km/P9GzIZCK674d4RV0CP5dvW1lTXU\nUj7KQ0pbDpWP/983zwwg8s2zW4mqQGF8XqtRN03QRuYMIoRo4VYzttYLfxdLrilx\ndxHJMDikFNGfepUg/kx7QT19OKIxwbhZCAtolSP6g+u3eqGFCIFyBO3Qf/bNT132\ngsEuvHRy6h3iNCIUDRZeWWOhfhrJBKHsmYcjpEyT+74JXMHRPapXJ/IRBjv4AxC9\nNyyqRqwsw4iW0BLy4jOlT4IGuI5I9CFSbaqF3mozIhXT3hOWOjQWF0oYpLehDblu\nxvjU37LpAgMBAAECggEAKm0j5EtuotipAD/xhmNhk+kR/DRavEbWNGOJ8uOMs7Vd\nEzGeE98LWdGGlGE58SnBK/uYCBK7YtH9INjXyGEShULNGmFVt/o/lptep5lq4y1U\nMakRimgVaZsE7CzPlAWnhJxPF4NApp1p4K6Ni1uDc0yPP2xIkCSqY1SUkN86/Fmp\ngwiG5J16ZReVYE59IDsqVsSkR6QxMnsbZcJLzBxazcJTxgvZex4wgF2e7T/47UEZ\nTYx9yxwDSODVnrBBzwCyY0+WRR+lB38Wyc+8DHRHgey5EcneXUfOgWJ+Hvgarn8Z\nyFxjYKkOGh0uT/OCUFhShP6CuzRB6ycGeMN1T8B2DwKBgQDcGIvGJ80mouetyxHj\njLFlRJDfetiNQvwpbqjhRDay08pDirsLtPBS3DwQof1acqt9S3FcpULqeFxLbDQg\nd0SRtoMfRR+KHHCN98WR6CwvWOjdQxwgashABAP/RObtu6f41kVa9ihcqq75guuO\noJ+vdltv4ZVvT/V/Z4bibLD02wKBgQDMvyCg3qg5M8KteqMc+x11ybcBxw5KLTv9\njNLS2sp+Avl7YMH4chBY2zH1kvUK97Cg2tuQwlcRsJbCvd3iCb9gT8VE0YbDHbQi\n05mv46exaIjpkgETIUGS0liOs8/uWkwQgdPDKHbwH1Vnc00hFdAmU11/s+lhTTKe\nNUefZPxAiwKBgGMijzqWzNndQHtQX2NeCL0zUAnJHGcsR8YluN2WSwjrSkx33V4d\nhq3b0xYu0J3/zmxmIc54BZb01aWHPEdvUSxMx+y6xsT/oFbhxlS8/cHpyyF2S+Hy\nFvZ2mJJPJ7Dm+HallKGvBGkQ3DU4mf8pLCPtLKxNMHDt1Acpy2CLUn1HAoGBALv4\nUDVAlUKG0ZjAuVVW+ZH00Y3ROL5CzwuVKMwpz7NmebKafxnfZkCdZD1nYI5kHYVf\nyCobMSJtc8tv0m+9sTPzqFDo54bkE0fR6gu/vmmyZdfBkjkE1BW+BU1lqWTTA3g4\nKLjHwoHq0lZ6VXolc4ZsDK+79Wu+GtWCZrHgXXHHAoGAHSgitwnQzj8jJ4AiLS5s\nZWf2SjbbDRz0S0P/PooXKVq/brqp5F9BTA/z43N/RkFbyFMKKkOU3B8H0ZD6BtGQ\ntm/i8R+w2XZz/2mB+diLengtdSTSQBmR3r3y9AXi0bBDFamIeukko5MdW3S8rmzX\nzzmYk22kNQkUZ/eaQ1cDZVc=\\n-----END PRIVATE KEY-----\\n",
  "client_email": "firebase-adminsdk-fbsvc@ai-interviewer-94aa7.iam.gserviceaccount.com",
  "client_id": "107878884646937962566",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40ai-interviewer-94aa7.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""